spring:
  application:
    name: webshell
  main:
    banner-mode: "off"
server:
  port: ${PORT:8001}
userpassword: "$2a$10$3/f1mY14mMqF7cGksN2g2uBZX/FbbuLeOSnQ6yUu9/.lLqmUj6B4e"
testpassword: "$2a$10$7r7G6TDECbA5N.yvChZJeuMhywmDKLfP373LEl6dj.SYCJ/vtAdOu"
