apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.istio.gatewayName }}
spec:
  selector:
    istio: ingressgateway
  servers:
    {{- if .Values.certManager.enabled }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
      {{- range .Values.istio.hosts }}
        - {{ . }}
      {{- end }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.istio.tls.secretName }}
    {{- end }}
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.istio.host }}
