apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.deploymentName }}-vs
spec:
  hosts:
    - {{ .Values.istio.host }}
  exportTo:
  - "."
  - istio-ingress
  - istio-system
  gateways:
    - {{ .Values.istio.gatewayName }}
    - mesh
  http:
    - route:
        - destination:
            host: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}
